version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - '3001:3001'
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
